TRUNCATE TABLE `adventure` ;
TRUNCATE TABLE `adventure_character` ;
TRUNCATE TABLE `event` ;
TRUNCATE TABLE `event_join`;
TRUNCATE TABLE `event_monster_spawn`;
TRUNCATE TABLE `event_character_attack`;
TRUNCATE TABLE `event_level_up`;
TRUNCATE TABLE `event_reward_experience`;
TRUNCATE TABLE `monster`;
TRUNCATE TABLE `persona`;
TRUNCATE TABLE `persona_statistic`;
TRUNCATE TABLE `adventure` ;
TRUNCATE TABLE `adventure_character` ;
TRUNCATE TABLE `event` ;
TRUNCATE TABLE `event_join`;
TRUNCATE TABLE `event_monster_spawn`;
TRUNCATE TABLE `event_character_attack`;
TRUNCATE TABLE `event_level_up`;
TRUNCATE TABLE `event_reward_experience`;
TRUNCATE TABLE `event_statistic_test`;
TRUNCATE TABLE `monster`;
TRUNCATE TABLE `persona`;
TRUNCATE TABLE `persona_statistic`;
